# Layers without Parameters

In [1]:
import torch
from torch import nn
from torch.nn import functional as F


In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

# Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.5806, -0.5167,  0.1851],
        [-0.2894,  1.8363, -0.4769],
        [ 0.2715, -2.6494,  1.1683],
        [ 0.6639, -0.3194,  0.2231],
        [-0.3029,  0.7091, -0.8232]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 1.0201],
        [0.0000, 0.0000, 0.8476]])

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[7.6934],
        [7.8223]])