# Computing Devices

In [1]:
import torch
from torch import nn

In [2]:
torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [3]:
torch.cuda.device_count() # The number of available GPUs

0

In [4]:
def try_gpu(i=0): #@save
    """Return gpu(i) if exists, otherwise return cpu()."""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus(): #@save
    """Return all available GPUs or [cpu(),] if no GPU exists."""
    devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

# Tensors and GPUs

In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

## Storage on the GPU

In [6]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.3599, 0.0283, 0.3423],
        [0.3626, 0.1449, 0.2670]])

# Neural Networks and GPUs

In [8]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu()) # Put the model parameters on the GPU

In [9]:
net(X)

tensor([[0.4557],
        [0.4557]], grad_fn=<AddmmBackward>)

In [10]:
net[0].weight.data.device

device(type='cpu')