In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True) # Same to x = torch.arange(4.0, requires_grad=True)
x.grad

In [4]:
y = 2 * torch.dot(x, x) # y = 2 X^T X
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [7]:
# Pytorch accumulates the gradient in default, we need to clear the previous values.
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

# Backward for Non-Scalr Variables

In [8]:
# Invoking `backward` on a non-scalar requires passing in a `gradient` argument
# which specifies the gradient of the differentiated function w.r.t `self`.
# In our case, we simply want to sum the partial derivatives, so passing in
# a gradient of ones is appropriate.
x.grad.zero_()
y = x * x
# y.backward(torch.ones(len(x))) # equivalent to the below
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

# Detaching Computation

In [9]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

# Computing the Gradient of Python Control Flow

In [11]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [13]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [14]:
a.grad == d/a

tensor(True)